CREATE TABLE ROOMS(
ROOM_ID NUMBER,
CONSTRAINT ROOM_ID_PK PRIMARY KEY (ROOM_ID),
ROOM_NUMBER_OF_GUESTS NUMBER NOT NULL,
ROOM_PRICE NOT NULL,
ROOM_BREAKFAST_INCLUDED NUMBER DEFAULT 1,
ROOM_RETS_ALLOVED NUMBER DEFAULT 0,
ROOM_DATE_AVIABLE_FROM TIMESTAMP NOT NULL,
HOTEL_ID NUMBER,
CONSTRAINT HOTEL_ID_FK FOREIGN KEY (HOTEL_ID) REFERENCES HOTELS (ID_HOTEL);