CREATE TABLE ORDERS(
ORDER_ID NUMBER,
CONSTRAINT ORDER_ID_PK PRIMARY KEY (ORDER_ID),
USER_ID NUMBER,
CONSTRAINT USER_ID_FK FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)),
ROOM_ID NUMBER,
CONSTRAINT ROOM_ID_FK FOREIGN KEY (ROOM_ID) REFERENCES ROOMS(ROOM_ID)),
DATE_FROM TIMESTAMP,
DATE_TO TIMESTAMP,
MONEY_PAID NUMBER;

ALTER TABLE ORDERS
  ADD AVIALABLE NUMBER(1,0) DEFAULT 1;