CREATE TABLE HOTELS(
ID_HOTEL NUMBER,
CONSTRAINT HOTEL_ID_PK PRIMARY KEY (ID_HOTEL),
HOTEL_NAME NVARCHAR2(50) NOT NULL UNIQUE,
HOTEL_COUNTRY NVARCHAR2(20) NOT NULL,
HOTEL_CITY NVARCHAR2(20) NOT NULL,
HOTEL_STREET NVARCHAR2(50) NOT NULL)